/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Dimensions { 'length' : number, 'width' : number }
export type FurnitureId = bigint;
export interface FurnitureItem {
  'id' : FurnitureId,
  'rotation' : number,
  'size' : Size,
  'type' : string,
  'furnitureLabel' : string,
  'position' : Position,
}
export type MoodBoardId = bigint;
export interface MoodBoardNote { 'id' : MoodBoardId, 'content' : string }
export interface Position { 'x' : number, 'y' : number }
export interface Room {
  'id' : RoomId,
  'name' : string,
  'furniture' : Array<FurnitureItem>,
  'dimensions' : Dimensions,
  'moodBoard' : Array<MoodBoardNote>,
}
export type RoomId = bigint;
export interface Size { 'height' : number, 'width' : number }
export interface _SERVICE {
  'addFurniture' : ActorMethod<
    [RoomId, string, string, Position, Size, number],
    FurnitureId
  >,
  'addMoodBoardNote' : ActorMethod<[RoomId, string], MoodBoardId>,
  'createRoom' : ActorMethod<[string, Dimensions], RoomId>,
  'deleteFurniture' : ActorMethod<[RoomId, FurnitureId], undefined>,
  'deleteMoodBoardNote' : ActorMethod<[RoomId, MoodBoardId], undefined>,
  'deleteRoom' : ActorMethod<[RoomId], undefined>,
  'getAllFurniture' : ActorMethod<[RoomId], Array<FurnitureItem>>,
  'getAllMoodBoardNotes' : ActorMethod<[RoomId], Array<MoodBoardNote>>,
  'getAllRooms' : ActorMethod<[], Array<Room>>,
  'getFurniture' : ActorMethod<[RoomId, FurnitureId], FurnitureItem>,
  'getMoodBoardNote' : ActorMethod<[RoomId, MoodBoardId], MoodBoardNote>,
  'getRoom' : ActorMethod<[RoomId], Room>,
  'updateFurniture' : ActorMethod<
    [RoomId, FurnitureId, string, string, Position, Size, number],
    undefined
  >,
  'updateMoodBoardNote' : ActorMethod<[RoomId, MoodBoardId, string], undefined>,
  'updateRoom' : ActorMethod<[RoomId, string, Dimensions], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];