/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomId = IDL.Nat;
export const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const Size = IDL.Record({
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const FurnitureId = IDL.Nat;
export const MoodBoardId = IDL.Nat;
export const Dimensions = IDL.Record({
  'length' : IDL.Float64,
  'width' : IDL.Float64,
});
export const FurnitureItem = IDL.Record({
  'id' : FurnitureId,
  'rotation' : IDL.Float64,
  'size' : Size,
  'type' : IDL.Text,
  'furnitureLabel' : IDL.Text,
  'position' : Position,
});
export const MoodBoardNote = IDL.Record({
  'id' : MoodBoardId,
  'content' : IDL.Text,
});
export const Room = IDL.Record({
  'id' : RoomId,
  'name' : IDL.Text,
  'furniture' : IDL.Vec(FurnitureItem),
  'dimensions' : Dimensions,
  'moodBoard' : IDL.Vec(MoodBoardNote),
});

export const idlService = IDL.Service({
  'addFurniture' : IDL.Func(
      [RoomId, IDL.Text, IDL.Text, Position, Size, IDL.Float64],
      [FurnitureId],
      [],
    ),
  'addMoodBoardNote' : IDL.Func([RoomId, IDL.Text], [MoodBoardId], []),
  'createRoom' : IDL.Func([IDL.Text, Dimensions], [RoomId], []),
  'deleteFurniture' : IDL.Func([RoomId, FurnitureId], [], []),
  'deleteMoodBoardNote' : IDL.Func([RoomId, MoodBoardId], [], []),
  'deleteRoom' : IDL.Func([RoomId], [], []),
  'getAllFurniture' : IDL.Func([RoomId], [IDL.Vec(FurnitureItem)], ['query']),
  'getAllMoodBoardNotes' : IDL.Func(
      [RoomId],
      [IDL.Vec(MoodBoardNote)],
      ['query'],
    ),
  'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getFurniture' : IDL.Func([RoomId, FurnitureId], [FurnitureItem], ['query']),
  'getMoodBoardNote' : IDL.Func(
      [RoomId, MoodBoardId],
      [MoodBoardNote],
      ['query'],
    ),
  'getRoom' : IDL.Func([RoomId], [Room], ['query']),
  'updateFurniture' : IDL.Func(
      [RoomId, FurnitureId, IDL.Text, IDL.Text, Position, Size, IDL.Float64],
      [],
      [],
    ),
  'updateMoodBoardNote' : IDL.Func([RoomId, MoodBoardId, IDL.Text], [], []),
  'updateRoom' : IDL.Func([RoomId, IDL.Text, Dimensions], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomId = IDL.Nat;
  const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const Size = IDL.Record({ 'height' : IDL.Float64, 'width' : IDL.Float64 });
  const FurnitureId = IDL.Nat;
  const MoodBoardId = IDL.Nat;
  const Dimensions = IDL.Record({
    'length' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const FurnitureItem = IDL.Record({
    'id' : FurnitureId,
    'rotation' : IDL.Float64,
    'size' : Size,
    'type' : IDL.Text,
    'furnitureLabel' : IDL.Text,
    'position' : Position,
  });
  const MoodBoardNote = IDL.Record({
    'id' : MoodBoardId,
    'content' : IDL.Text,
  });
  const Room = IDL.Record({
    'id' : RoomId,
    'name' : IDL.Text,
    'furniture' : IDL.Vec(FurnitureItem),
    'dimensions' : Dimensions,
    'moodBoard' : IDL.Vec(MoodBoardNote),
  });
  
  return IDL.Service({
    'addFurniture' : IDL.Func(
        [RoomId, IDL.Text, IDL.Text, Position, Size, IDL.Float64],
        [FurnitureId],
        [],
      ),
    'addMoodBoardNote' : IDL.Func([RoomId, IDL.Text], [MoodBoardId], []),
    'createRoom' : IDL.Func([IDL.Text, Dimensions], [RoomId], []),
    'deleteFurniture' : IDL.Func([RoomId, FurnitureId], [], []),
    'deleteMoodBoardNote' : IDL.Func([RoomId, MoodBoardId], [], []),
    'deleteRoom' : IDL.Func([RoomId], [], []),
    'getAllFurniture' : IDL.Func([RoomId], [IDL.Vec(FurnitureItem)], ['query']),
    'getAllMoodBoardNotes' : IDL.Func(
        [RoomId],
        [IDL.Vec(MoodBoardNote)],
        ['query'],
      ),
    'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getFurniture' : IDL.Func(
        [RoomId, FurnitureId],
        [FurnitureItem],
        ['query'],
      ),
    'getMoodBoardNote' : IDL.Func(
        [RoomId, MoodBoardId],
        [MoodBoardNote],
        ['query'],
      ),
    'getRoom' : IDL.Func([RoomId], [Room], ['query']),
    'updateFurniture' : IDL.Func(
        [RoomId, FurnitureId, IDL.Text, IDL.Text, Position, Size, IDL.Float64],
        [],
        [],
      ),
    'updateMoodBoardNote' : IDL.Func([RoomId, MoodBoardId, IDL.Text], [], []),
    'updateRoom' : IDL.Func([RoomId, IDL.Text, Dimensions], [], []),
  });
};

export const init = ({ IDL }) => { return []; };