/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Position {
    x: number;
    y: number;
}
export interface Size {
    height: number;
    width: number;
}
export type FurnitureId = bigint;
export type MoodBoardId = bigint;
export type RoomId = bigint;
export interface Room {
    id: RoomId;
    name: string;
    furniture: Array<FurnitureItem>;
    dimensions: Dimensions;
    moodBoard: Array<MoodBoardNote>;
}
export interface Dimensions {
    length: number;
    width: number;
}
export interface FurnitureItem {
    id: FurnitureId;
    rotation: number;
    size: Size;
    type: string;
    furnitureLabel: string;
    position: Position;
}
export interface MoodBoardNote {
    id: MoodBoardId;
    content: string;
}
export interface backendInterface {
    addFurniture(roomId: RoomId, type: string, furnitureLabel: string, position: Position, size: Size, rotation: number): Promise<FurnitureId>;
    addMoodBoardNote(roomId: RoomId, content: string): Promise<MoodBoardId>;
    createRoom(name: string, dimensions: Dimensions): Promise<RoomId>;
    deleteFurniture(roomId: RoomId, furnitureId: FurnitureId): Promise<void>;
    deleteMoodBoardNote(roomId: RoomId, noteId: MoodBoardId): Promise<void>;
    deleteRoom(id: RoomId): Promise<void>;
    getAllFurniture(roomId: RoomId): Promise<Array<FurnitureItem>>;
    getAllMoodBoardNotes(roomId: RoomId): Promise<Array<MoodBoardNote>>;
    getAllRooms(): Promise<Array<Room>>;
    getFurniture(roomId: RoomId, furnitureId: FurnitureId): Promise<FurnitureItem>;
    getMoodBoardNote(roomId: RoomId, noteId: MoodBoardId): Promise<MoodBoardNote>;
    getRoom(id: RoomId): Promise<Room>;
    updateFurniture(roomId: RoomId, furnitureId: FurnitureId, type: string, furnitureLabel: string, position: Position, size: Size, rotation: number): Promise<void>;
    updateMoodBoardNote(roomId: RoomId, noteId: MoodBoardId, content: string): Promise<void>;
    updateRoom(id: RoomId, name: string, dimensions: Dimensions): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFurniture(arg0: RoomId, arg1: string, arg2: string, arg3: Position, arg4: Size, arg5: number): Promise<FurnitureId> {
        if (this.processError) {
            try {
                const result = await this.actor.addFurniture(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFurniture(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addMoodBoardNote(arg0: RoomId, arg1: string): Promise<MoodBoardId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMoodBoardNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMoodBoardNote(arg0, arg1);
            return result;
        }
    }
    async createRoom(arg0: string, arg1: Dimensions): Promise<RoomId> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0, arg1);
            return result;
        }
    }
    async deleteFurniture(arg0: RoomId, arg1: FurnitureId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFurniture(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFurniture(arg0, arg1);
            return result;
        }
    }
    async deleteMoodBoardNote(arg0: RoomId, arg1: MoodBoardId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMoodBoardNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMoodBoardNote(arg0, arg1);
            return result;
        }
    }
    async deleteRoom(arg0: RoomId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoom(arg0);
            return result;
        }
    }
    async getAllFurniture(arg0: RoomId): Promise<Array<FurnitureItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFurniture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFurniture(arg0);
            return result;
        }
    }
    async getAllMoodBoardNotes(arg0: RoomId): Promise<Array<MoodBoardNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMoodBoardNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMoodBoardNotes(arg0);
            return result;
        }
    }
    async getAllRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRooms();
            return result;
        }
    }
    async getFurniture(arg0: RoomId, arg1: FurnitureId): Promise<FurnitureItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getFurniture(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFurniture(arg0, arg1);
            return result;
        }
    }
    async getMoodBoardNote(arg0: RoomId, arg1: MoodBoardId): Promise<MoodBoardNote> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodBoardNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodBoardNote(arg0, arg1);
            return result;
        }
    }
    async getRoom(arg0: RoomId): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoom(arg0);
            return result;
        }
    }
    async updateFurniture(arg0: RoomId, arg1: FurnitureId, arg2: string, arg3: string, arg4: Position, arg5: Size, arg6: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFurniture(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFurniture(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateMoodBoardNote(arg0: RoomId, arg1: MoodBoardId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMoodBoardNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMoodBoardNote(arg0, arg1, arg2);
            return result;
        }
    }
    async updateRoom(arg0: RoomId, arg1: string, arg2: Dimensions): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoom(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoom(arg0, arg1, arg2);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
